### ISSUE TITLE
Hanlon logging happening on cli side

### ISSUE THREAD

**Issue by sankarvema** [csc/Hanlon#113]
Not sure if this is the intended behavior...

Max. hanlon logging is happening on the client end under cli/log/project_hanlon.log while server side log file web/log/project_hanlon.log is almost empty. This includes even the db information, image files paths, image names which are generally considered sensitive to expose to client end components and mostly restricted to server side.

For Hanlon, as per the current spec, is mostly a monolithic piece and intended to run behind the firewall; this may not be a major security concern. But later when we try to split client and server components (which we already started by logically separating cli and web) this would be a concern. 

Further when Hanlon starts running in a data center scenario, with client components accessing Hanlon over firewal this would prove to be a major security lapse

Log Snapshot (under debug mode)
Simple cli/hanlon creates a 31.7 kb file while server side is just one liner (the header)

Client contains information like 
D, [2014-07-11T12:00:53.288000 #6345] DEBUG -- /home/user/ohan/Is89-fix/core/image_service/base.rb:196:in `get_dir_hash'>>ProjectHanlon::ImageService::OSInstall#get_dir_hash: Generating hash for path: /home/user/ohan/Is89-fix/image/os/2qBDwxlfBm6y39nKguGYAT
D, [2014-07-11T12:00:53.292000 #6345] DEBUG -- /home/user/ohan/Is89-fix/core/image_service/base.rb:196:in `get_dir_hash'>>ProjectHanlon::ImageService::MicroKernel#get_dir_hash: Generating hash for path: /home/user/ohan/Is89-fix/image/mk/7hP7P6jOsrs9I6vvQkVUYr
E, [2014-07-11T12:00:53.294000 #6345] ERROR -- /home/user/ohan/Is89-fix/core/image_service/microkernel.rb:52:in `verify'>>ProjectHanlon::ImageService::MicroKernel#verify: ISO file structure

Server side is just
# Logfile created on 2014-07-13 09:56:43 -0400 by logger.rb/v1.2.7

**Comment by tjmcs** [comment]
This issue has been closed by refactoring that has happened since it was opened. The RESTful server is now logging it's own errors.
