### ISSUE TITLE
Rake Spec: Use rake for all Hanlon build activities

### ISSUE THREAD

**Issue by sankarvema** [csc/Hanlon#130]
1.	Rake Init: Shall initialize Hanlon development, quality, and production environments
a.	Create and validate default configuration files
b.	Initialize Hanlon DB
c.	Initialize Hanlon Properties files with current set of product properties like version, license & copyright information
2.	Rake Validate: Shall validate Hanlon current instance to check if …
a.	Configuration files are valid
b.	All the application modules are validate
c.	Necessary environment variables are defined with valid data elements
d.	Database instance is fine and stable. Hanlon server can establish proper connection
3.	Rake Migrate: Shall migrate Razor environment to Hanlon
a.	Replace existing Razor application code with Hanlon application modules
b.	Migrate existing Razor data objects to Hanlon objects
4.	Rake Info: Shall build and return necessary Hanlon information which can be used across Hanlon application
a.	Return Hanlon version information [ToDo:: identify suitable logic to build version information]
b.	Return Hanlon License & Copyright information
5.	Rake Build: Shall create deployable Hanlon module for different environments
a.	Build hanlon.war file to deploy Hanlon server under Java App Servers
b.	Build hanlon-client.deb/.rpm to deploy Hanlon client on any client machine

**Comment by tjmcs** [comment]
We are no longer supporting Rakefile builds of Hanlon, closing as no longer applicable
