### ISSUE TITLE
New Model Request - CoreOS

### ISSUE THREAD

**Issue by bunchc** [csc/Hanlon#177]
I posted over at the Google Group, but it's pretty dead over there. I'd love to add a model for CoreOS. It's boot to ram does offer an interesting challenge on reboots however.

Thoughts on the right way to go about this? More info on the CoreOS PXE stuff here:
https://coreos.com/docs/running-coreos/bare-metal/booting-with-pxe/

**Comment by hh** [comment]
:+1:

**Comment by hh** [comment]
I might be taking a look at this again soon

**Comment by hh** [comment]
I might be taking a look at this again soon.... https://coreos.com/docs/running-coreos/bare-metal/booting-with-pxe/
