### ISSUE TITLE
PostgreSql adapter not migrated to jruby

### ISSUE THREAD

**Issue by sankarvema** [csc/Hanlon#245]
Hanlon DB layer is created with ruby postgres adapter "ruby gem pg"  which is a native C gem under ruby. After migrating to jruby this gem is supposely migrated to 'jdbc-postgres'. But the current code based still refers to pg gem. line 2 postgres_plugin.rb  refers to 'require pg'. This gives the impression that code needs to be migrated and tested under jdbc-postgre.

**Comment by tjmcs** [comment]
JRuby is no longer a supported platform for Hanlon, so this issue is no longer applicable
