### ISSUE TITLE
Implement a generic DB design for Hanlon to support multiple Databases

### ISSUE THREAD

**Issue by sankarvema** [csc/Hanlon#281]
Extending Hanlon persistance layer design to support other popular databases would help the community users in using Hanlon along with current database installations.

In the current form, Hanlon is designed to support to Mongo and PostgreSql. However, as per issue #245, after migration to Java stack postgre db component is migrated and tested on Java stack. We need to redesign Hanlon persistance layer to be more generic to support both RDBMS and NoSQL style database. This design should also address the needs of #181 & #226 so that Hanlon databases can be easily migrated from any on DB to another DB giving complete freedom to users

**Comment by tjmcs** [comment]
This issue has not been update recently and appears to be closed by the changes that were made to add Cassandra support to Hanlon; closing
