### ISSUE TITLE
Decouple config parameters from persistance layer

### ISSUE THREAD

**Issue by sankarvema** [csc/Hanlon#290]
In the current implementation db layer directly accesses config instance to retrieve DB connection parameters. This is making it difficult to use persistence layer for other features (like for eg. hanlon migration). We need to refactor this layer to remove direct references of config instance under /core/persist/

**Comment by tjmcs** [comment]
Closed by PRs made over the past year to separate out the configuration parameters for various persistence layer types from the core Hanlon server configuration
