### ISSUE TITLE
Node discovery of a baremetal server via IPXE and "fixed-address" in DHCP configuration, doesn't work.

### ISSUE THREAD

**Issue by venkymullapudi** [csc/Hanlon#314]
After adding the image(microkernel and RHEL 6 ISO), model, policy(with only one tag, memsize_4GiB). The node doesn't get discovered. The outputs and the dhcpd.conf file is below. I am using "fixed-address" parameter in the DHCP configuration.
Is there supposed to be more than one tag for the policy (tried different combinations over that too) ?

# hanlon image get all
fatal: Not a git repository (or any of the parent directories): .git
Images:
         UUID                 Type                     ISO Filename              Status
7jOqhehCiN5W6dltvVGhGI  MicroKernel Image  hnl_mk_dev-image.1.0.iso              Valid
5zfQGnhpEips0qHJfTrVGH  OS Install         Build-RHEL6_5-x86_64.iso  Valid

# hanlon model get all
fatal: Not a git repository (or any of the parent directories): .git
Models:
   Label       Template     Description             UUID
install_soe  linux_deploy  RedHat 6 Model  1xm9mHAuVslsGDcvBhjzqk

# hanlon policy get all
fatal: Not a git repository (or any of the parent directories): .git
Policies:
#  Enabled       Label            Tags       Model Label  #/Max  Counter           UUID
0  true     rhel6soe_policy  [memsize_4GiB]  install_soe  0/-    0        3ojg8tn70PpmYm4rtn6350

# hanlon node get all
fatal: Not a git repository (or any of the parent directories): .git
Discovered Nodes
< none >

# cat /etc/dhcp/dhcpd.conf
subnet 10.5.68.0 netmask 255.255.255.0 {
host baremetal {
        hardware ethernet 00:19:BC:3C:63:6E;
        fixed-address 10.53.68.162;
        }
  option subnet-mask 255.255.255.0;
  option broadcast-address 10.53.68.255;
  option routers 10.53.68.1;
  filename "pxelinux.0"; # default loading
  next-server 10.53.68.217;
}

**Comment by tjmcs** [comment]
I couldn't help but notice in the output you provided (above), @venkymullapudi, that you were using an older (v1.0) version of the Hanlon Microkernel.  I'm assuming you are using this with a more recent release of Hanlon (the latest is v2.0.0).  Could you please download the latest Hanlon Microkernel (available [here](https://github.com/csc/Hanlon-Microkernel/releases/latest)) and try again?  I'm not sure that we've thoroughly tested using an older release of the Microkernel with a newer release of Hanlon, so testing with the latest of both will ensure that it's not a versioning problem.

**Comment by venkymullapudi** [comment]
I have downloaded the v2.0.0 Hanlon Microkernel and tried, but the result is the same. I will try in a few more combinations, now.

**Comment by tjmcs** [comment]
Any updates on this issue @venkymullapudi? If not I will close it out (and let you reopen if you are still having this issue)

**Comment by venkymullapudi** [comment]
Thanks... This can be closed.
