### ISSUE TITLE
Add ability to specify **logical or** of tags for policies

### ISSUE THREAD

**Issue by tjmcs** [csc/Hanlon#340]
To minimize the number of policies needed to deploy a cluster of nodes (say a VSAN cluster or an OpenStack cloud), it would be helpful if we could create a policy that bound nodes to an underlying model using a **logical or** of tags rather than an **and** of tags. Here, I'm thinking of an argument to the Hanlon CLI that would look something like the following:
```
$ hanlon policy add -p linux_deploy -t '000C29FE8355|000C29AECE0B|000C29A936AF' ...
```
where the tags are separated by an **or** bar (i.e. the `|` character). Obviously, we'd also have to support an equivalent enhancement in the underlying RESTful interface, but it shouldn't be too difficult. This format for specifying the tags used by a policy when binding an underlying model to a node would be supported in addition to the current format supported for this command, which looks like this:
```
$ hanlon policy add -p linux_deploy -t 'nics_1,memsize_2GiB' ...
```
the difference would be that in the first case we'd perform an **or** operation to determine if a node matched to the policy, while in the second (the existing form) we'd perform an **and** operation (i.e. the first policy would match if the node was tagged with a tag of `000C29FE8355` **or** `000C29AECE0B` **or**  `000C29A936AF` while the second policy would only match if the node was tagged with both the `nics_1` tag **and** the `memsize_2GiB` tag).

**Comment by hh** [comment]
https://github.com/csc/Hanlon/wiki/policy should be updated for clarification particularly how this should look via the API, and the help output should be updated at well currently only mentions ```,```
