### ISSUE TITLE
Docker build is failing

### ISSUE THREAD

**Issue by mtnbikenc** [csc/Hanlon#342]
The latest update to the Dockerfile is causing the build to fail because the ruby2.2.0 package is not available in the default repository.

`E: Unable to locate package ruby2.2.0`

**Comment by mtnbikenc** [comment]
Introduced in #330.

**Comment by tjmcs** [comment]
how would you like to resolve this, @mtnbikenc?  Can you submit a PR to roll back to an earlier version of Ruby in the Docker container?
