### ISSUE TITLE
hanlon node option for --list-by-hw-id

### ISSUE THREAD

**Issue by hh** [csc/Hanlon#359]
Tags are autocreated by this field, and it's static across mulitple hanlon instances, it would be nice to see it as an option to list them all.

**Comment by tjmcs** [comment]
Was thinking this might be better if we could extend it to support more than just this one parameter. Perhaps a filter that you can use to setup the fields you're interested in seeing in the output of the node command (with a default set that returns the current view)?

**Comment by hh** [comment]
I've been doing it in the hanlon-api-ruby by just downloading all the models and doing a generic filter on all models https://github.com/hh/hanlon-api-ruby/blob/master/lib/hanlon/api/resource.rb#L108

**Comment by hh** [comment]
Might be interesting to provide a generic filter for all slices in a similar manner.

**Comment by hh** [comment]
(while I do use the cmdline, most of my need is around the API)

**Comment by tjmcs** [comment]
I would expect that any such filter would be passed through to the underlying RESTful API, so it would mean an additional argument to the appropriate RESTful API call(s). And yes, I do think we could add the same feature to other slices, but my plan was to start with the node slice and add it to others as we identify a need for it...sound like a plan?

**Comment by hh** [comment]
On Mon, Mar 23, 2015 at 11:29 AM, tjmcs <notifications@github.com> wrote:

> I would expect that any such filter would be passed through to the
> underlying RESTful API, so it would mean an additional argument to the
> appropriate RESTful API call(s). And yes, I do think we could add the same
> feature to other slices, but my plan was to start with the node slice and
> add it to others as we identify a need for it...sound like a plan?
>

I also needed to find active_models by policy and found a few other use
cases as well (hence my hack in the client side). I'll document those as I
find so we can have a broader view.

**Comment by tjmcs** [comment]
Do keep in mind that what I'm talking about is just a change to the CLI; the RESTful API actually returns a lot more information than is shown on the command-line, so you may actually already have the information in the RESTful response that you need...or at least the means to obtain it from another RESTful call :)
