### ISSUE TITLE
Isolate config.db_name from persisitance layer

### ISSUE THREAD

**Issue by sankarvema** [csc/Hanlon#361]
Problem: persist/controller.rb directly works with config parameters whose parametric name change for db migration. This should be changed to pass db connection parameters to db initializer instead of directly reading from config file

Objective: persist/mongo_plugin.rb and persist/postgres_plugin.rb directly retrieves db_name from comfig file making it difficult for the caller to change the db_name. This is required for hanlon DB migrator to have necessary flexibility to work with different databases when migrating from old implemnetation to the newer one. Otherwise it would lead to code duplication

**Comment by tjmcs** [comment]
Changes made to support alternate database configurations (Cassandra support for example) over the past year have made this issue no longer applicable; closing
