### ISSUE TITLE
cloud_init.datasources issue in rancher/os 0.4.5

### ISSUE THREAD

**Issue by hh** [csc/Hanlon#433]
Somewhere around version https://github.com/rancher/os/releases/tag/v0.4.4 the way RancherOS processes /proc/cmdline, particularly rancher.cloud_init.datasources changed.

```
[root@rancher ~]# cat /proc/cmdline 
rancher.password=test1234 rancher.cloud_init.datasources=[url:http://1.1.1.6:8026/hanlon/api/v1/image/mk/UVcw9vD9aEgd947RMPSJ1/cloud-config] smbios_uuid
=00000000-0000-0000-0000-00259097D478
```

```
[root@rancher ~]# cloud-init -execute
....
data=map[rancher:map[password:test1234 cloud_init:map[datasources:[url:http://1.1.1.6:8026/hanlon/api/v1/image/mk/UVcw9vD9aEgd947RMPSJ1/cloud-config]]]
] err=Cannot resolve [url:http://1.1.1.6:8026/hanlon/api/v1/image/mk/UVcw9vD9aEgd947RMPSJ1/cloud-config] into <[]string Value> at line 105, column 17
```

**Comment by hh** [comment]
Since it's a backwards incompatible breaking change with regards to the kernel level parameters, it'll probably require some thought on how to address this.

**Comment by hh** [comment]
[ProjectHanlon::PolicyTemplate::BootMK.get_boot_script](https://github.com/csc/Hanlon/blob/7b7cfbe0413ce81d98c500c78b6fd1476de1cfcd/core/policy/boot_mk.rb#L37) set's rancher.cloud_init.datasource

```
        boot_script << " rancher.cloud_init.datasources=[url:#{image_svc_uri}/cloud-config]"
```

Still looking for where it's processed in rancheros.

I think it's [rancher/os cmd/cloudinit/cloudinit.go in currentDatasource](https://github.com/rancher/os/blob/master/cmd/cloudinit/cloudinit.go#L105)

**Comment by jcpowermac** [comment]
@hh modifing the line to 
```
" rancher.cloud_init.datasources=['url:#{image_svc_uri}/cloud-config']"
```
resolves this issue.  I tried this last night along with your PR.  From the documentation its supposed to be single quoted.

**Comment by hh** [comment]
@jcpowermac thanks for finding that, where did you see it in the documentation?
