### ISSUE TITLE
Hanlon Server Initialization Script

### ISSUE THREAD

**Issue by sankarvema** [csc/Hanlon#49]
Perform house keeping & validation activities on initializing Hanlon web. This should take care of activities like

1. Check and validate configuration files
2. Check the existence & access to proper image folder
3. Ensure running status of database server

... ** *please add any other issues you came across* **

On any of the validation issues, hanlon web instance should exit graceful with meaningful messages. In the absence of this, hanlon is throwing exception with vague messages

**Comment by tjmcs** [comment]
This issue can be closed, the hanlon_init.sh script that was added to Hanlon since this issue was opened should resolve it.
