### ISSUE TITLE
Cleanup PuppetLabs packaging automation support in Rakefile

### ISSUE THREAD

**Issue by mtnbikenc** [csc/Hanlon#75]
PuppetLabs packaging automation support exists in Rakefile however supporting ext/build_defaults.yaml has been removed from the project.  If this automation is no longer needed, the rest of the automation code should be removed.  Alternatively, add the missing build_defaults back into the project.

If no longer needed, remove `require 'yaml'`.

**Comment by tjmcs** [comment]
we are no longer supporting a Rakefile build, closing this issue as no longer applicable
